// Selectors
export const $parametersSwitchImg = document.querySelector('#parameters-header img')
export const $passwordLength      = document.querySelector('#length')
export const $passwordParameters  = document.querySelector("#parameters")
export const $letters             = document.querySelector('#letters')
export const $letterOptions       = document.querySelectorAll('input.letter-option')
export const $digits              = document.querySelector('#digits')
export const $specialSymbols      = document.querySelector('#special-symbols')
export const $customSS            = document.querySelector('#custom-special-symbols')
export const $generatedPassword   = document.querySelector('#generated-password')
export const $generateButton      = document.querySelector('#generate')
export const $copyButton          = document.querySelector('#copy')
export const $visionSwitch        = document.querySelector('#vision-switch')
export const $visionSwitchImg     = document.querySelector('#vision-switch img')
export const $messageField        = document.querySelector('#message small')